baseURL = 'https://example.org/'
languageCode = 'en-us'
theme = 'PaperMod'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
[languages]

  [languages.en]
    contentDir = 'content/en/'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'dosh blog'
    weight = 1
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'

  [languages.ja]
  contentDir = 'content/ja/'
  disabled = false
  languageCode = 'ja-JP'
  languageDirection = 'ltr'
  languageName = 'æ—¥æœ¬èª'
  title = 'dosh blog'
  weight = 2
  [languages.ja.params]
      subtitle = 'ãƒªãƒ•ã‚¡ãƒ¬ãƒ³ã‚¹ã€ãƒãƒ¥ãƒ¼ãƒˆãƒªã‚¢ãƒ«ã€èª¬æ˜'


[params]

 [params.homeInfoParams]
   Title = "Home"
   #Content = ""
 [[params.socialIcons]]
   name = "Twitter"
   url = "https://twitter.com/d_osh8"
 [[params.socialIcons]]
   name = "github"# ğŸª¸ Welcome ğŸª¸
   url = "https://"




[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'Algotrade'
    pageRef = '/Algotrade/'
    weight = 20